version: '3.2'

services:

  backend:
    build:
      args:
        - POSTGRES_DSN=postgresql://postgres:123456@postgres:5432/videoroom
    command: python -m videoroom.backend.server --debug
    ports:
      - 7000:80
