"""empty message

Revision ID: 06291fb8bb58
Revises: d2a1bd897681
Create Date: 2020-10-27 17:49:13.611535

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '06291fb8bb58'
down_revision = 'd2a1bd897681'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('refresh_token', sa.String(), nullable=True))
    op.add_column('user', sa.Column('token_expired_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('user', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_user_refresh_token'), 'user', ['refresh_token'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_refresh_token'), table_name='user')
    op.alter_column('user', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('user', 'token_expired_at')
    op.drop_column('user', 'refresh_token')
    # ### end Alembic commands ###
