"""Added model ConfirmedToken

Revision ID: e7778072401a
Revises: 
Create Date: 2020-10-02 20:23:25.043572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7778072401a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('confirm_token',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('expired', sa.DateTime(), nullable=True),
    sa.Column('confirmed', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_confirm_token_email'), 'confirm_token', ['email'], unique=False)
    op.create_index(op.f('ix_confirm_token_token'), 'confirm_token', ['token'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_confirm_token_token'), table_name='confirm_token')
    op.drop_index(op.f('ix_confirm_token_email'), table_name='confirm_token')
    op.drop_table('confirm_token')
    # ### end Alembic commands ###
